// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TransferenciaMateriais.Infrastructure.Data;

#nullable disable

namespace TransferenciaMateriais.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TransferenciaMateriais.Domain.Entities.Anexo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ContentType")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("CorrelationType")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("FileName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<long?>("SizeBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("StorageRef")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<DateTimeOffset>("UploadedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UploadedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Tipo");

                    b.HasIndex("CorrelationType", "CorrelationId");

                    b.ToTable("anexo", (string)null);
                });

            modelBuilder.Entity("TransferenciaMateriais.Domain.Entities.AuditoriaEvento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ActorId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ActorRole")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("CorrelationType")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<int>("EventType")
                        .HasColumnType("integer");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("EventType", "Timestamp");

                    b.HasIndex("CorrelationType", "CorrelationId", "Timestamp");

                    b.ToTable("auditoria_evento", (string)null);
                });

            modelBuilder.Entity("TransferenciaMateriais.Domain.Entities.NotaFiscal", b =>
                {
                    b.Property<string>("ChaveAcesso")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<string>("CnpjDestinatario")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("CnpjEmitente")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DataEmissao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("MotivoCategoria")
                        .HasColumnType("integer");

                    b.Property<string>("MotivoDetalhe")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Numero")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTimeOffset?>("ReceivedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Serie")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ValidacaoStatus")
                        .HasColumnType("integer");

                    b.Property<string>("XmlRef")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("ChaveAcesso");

                    b.HasIndex("DataEmissao");

                    b.HasIndex("Tipo", "ValidacaoStatus");

                    b.ToTable("nfe", (string)null);
                });

            modelBuilder.Entity("TransferenciaMateriais.Domain.Entities.Notificacao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Assunto")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Corpo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("CorrelationType")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DestinatariosCc")
                        .HasColumnType("text");

                    b.Property<string>("DestinatariosTo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Erro")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("ProviderMessageId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset?>("SentAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CorrelationType", "CorrelationId");

                    b.HasIndex("Status", "Tipo");

                    b.ToTable("notificacao_email", null, t =>
                        {
                            t.HasCheckConstraint("CHK_notificacao_status_enum", "status IN ('ENFILEIRADA', 'ENVIADA', 'FALHOU')");
                        });
                });

            modelBuilder.Entity("TransferenciaMateriais.Domain.Entities.OrdemCompra", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("OsId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Numero")
                        .IsUnique();

                    b.HasIndex("OsId", "Status");

                    b.ToTable("oc", (string)null);
                });

            modelBuilder.Entity("TransferenciaMateriais.Domain.Entities.OrdemServico", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly?>("DataEstimadaEntrega")
                        .HasColumnType("date");

                    b.Property<string>("FilialDestinoId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("FluxType")
                        .HasColumnType("integer");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal>("QuantidadePlanejada")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)");

                    b.Property<int>("StatusWorkflow")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("FluxType");

                    b.HasIndex("Numero")
                        .IsUnique();

                    b.HasIndex("FilialDestinoId", "StatusWorkflow");

                    b.ToTable("os", null, t =>
                        {
                            t.HasCheckConstraint("CHK_os_quantidadePlanejada_pos", "quantidade_planejada > 0");
                        });
                });

            modelBuilder.Entity("TransferenciaMateriais.Domain.Entities.Pendencia", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("CorrelationType")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(800)
                        .HasColumnType("character varying(800)");

                    b.Property<DateTimeOffset?>("DueAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OwnerRole")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTimeOffset?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DueAt");

                    b.HasIndex("CorrelationType", "CorrelationId");

                    b.HasIndex("Tipo", "Status");

                    b.ToTable("pendencia", null, t =>
                        {
                            t.HasCheckConstraint("CHK_pendencia_status_enum", "status IN ('ABERTA', 'EM_ANDAMENTO', 'RESOLVIDA', 'CANCELADA')");
                        });
                });

            modelBuilder.Entity("TransferenciaMateriais.Domain.Entities.ProcessedMessage", b =>
                {
                    b.Property<string>("IdempotencyKey")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("Source")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Error")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTimeOffset?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("ReceivedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("IdempotencyKey", "Source");

                    b.HasIndex("Source", "IdempotencyKey");

                    b.ToTable("processed_message", (string)null);
                });

            modelBuilder.Entity("TransferenciaMateriais.Domain.Entities.Vinculo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("DivergenciaQuantidade")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)");

                    b.Property<string>("NfeChaveAcesso")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<string>("Observacao")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid?>("OcId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("OsId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("NfeChaveAcesso");

                    b.HasIndex("OcId");

                    b.HasIndex("OsId");

                    b.HasIndex("Status");

                    b.HasIndex("OsId", "OcId", "NfeChaveAcesso")
                        .IsUnique();

                    b.ToTable("vinculo", (string)null);
                });

            modelBuilder.Entity("TransferenciaMateriais.Domain.Entities.OrdemCompra", b =>
                {
                    b.HasOne("TransferenciaMateriais.Domain.Entities.OrdemServico", "OrdemServico")
                        .WithMany("OrdensCompra")
                        .HasForeignKey("OsId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("OrdemServico");
                });

            modelBuilder.Entity("TransferenciaMateriais.Domain.Entities.Vinculo", b =>
                {
                    b.HasOne("TransferenciaMateriais.Domain.Entities.NotaFiscal", "NotaFiscal")
                        .WithMany("Vinculos")
                        .HasForeignKey("NfeChaveAcesso")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TransferenciaMateriais.Domain.Entities.OrdemCompra", "OrdemCompra")
                        .WithMany("Vinculos")
                        .HasForeignKey("OcId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TransferenciaMateriais.Domain.Entities.OrdemServico", "OrdemServico")
                        .WithMany("Vinculos")
                        .HasForeignKey("OsId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("NotaFiscal");

                    b.Navigation("OrdemCompra");

                    b.Navigation("OrdemServico");
                });

            modelBuilder.Entity("TransferenciaMateriais.Domain.Entities.NotaFiscal", b =>
                {
                    b.Navigation("Vinculos");
                });

            modelBuilder.Entity("TransferenciaMateriais.Domain.Entities.OrdemCompra", b =>
                {
                    b.Navigation("Vinculos");
                });

            modelBuilder.Entity("TransferenciaMateriais.Domain.Entities.OrdemServico", b =>
                {
                    b.Navigation("OrdensCompra");

                    b.Navigation("Vinculos");
                });
#pragma warning restore 612, 618
        }
    }
}
