namespace TransferenciaMateriais.Domain.Enums;

/// <summary>
/// Tipo de evento de auditoria (enum canônico).
/// </summary>
public enum AuditoriaEventType
{
    OS_CRIADA,
    OS_DATA_ESTIMADA_ATUALIZADA,
    MATERIAL_FABRICADO,
    ROMANEIO_CONFERIDO,
    NFE_EMITIDA,
    NFE_XML_OBTIDO,
    FISCAL_NFE_VALIDADA,
    VINCULO_CRIADO,
    VINCULO_CORRIGIDO,
    ERRO_VINCULO_IDENTIFICADO,
    ESTOQUE_ORIGEM_ATUALIZADO,
    NFE_SAIDA_ORIGEM_EMITIDA,
    CHEGADA_MATERIAL_DESTINO,
    ANEXO_ADICIONADO,
    ENTRADA_DESTINO_CONCLUIDA,
    PENDENCIA_ABERTA,
    PENDENCIA_RESOLVIDA,
    NOTIFICACAO_ENFILEIRADA,
    NOTIFICACAO_ENVIADA,
    NOTIFICACAO_FALHOU,
    MEDICAO_APROVADA,
    MEDICAO_REPROVADA,
    CAMINHAO_NO_LOCAL,
    WORKFLOW_TRANSICAO,
    PROCESSO_CANCELADO
}
